[phases.setup]
nixPkgs = ["nodejs_20", "python3"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --omit=optional"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run preview"

